#repository = "binary"
repository = "text"
#repository = "inmemory"
#students = "students.pkl"
students = "students.txt"
#students = ""
#disciplines = "disciplines.pkl"
disciplines = "disciplines.txt"
#disciplines = ""
#grades = "grades.pkl"
grades = "grades.txt"
#grades = ""